# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifact

trigger:
master
pool:
  vmImage: 'go-latest'

steps:
- task: Gradle@1
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: 'latest-default'
    publishJUnitResults: 'true'
    testResultsFiles: 'CodeQL'
    tasks: 'assembleDebug'
