# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
master

pool:
  vmImage: 'latest'

steps:
 task: Gradle@4
  inputs:
    workingDirectory: 'master'
    gradleWrapperFile: 'gradlew'
    gradleOptions: 'latest'
    publishJUnitResults: true
    testResultsFiles: '/TEST-.xml'
    tasks: 'assembleDebug'
